### ISSUE TITLE
D3 animations are still active when we switch from dashboard to profile page

### ISSUE THREAD

**Issue by nareshbhatia** [archfirst/angular-patterns#8]
1. Open the debugger console
2. Switch from dashboard to profile page
3. Resize the window

You will see error messages from D3 trying to do animations (the tick function is being called)

**Comment by Ghary** [comment]
I have created a pull request which resolves this issue.
A proper function reference was not passed. Off() method was unable to find matching listener to unbind.

**Comment by nareshbhatia** [comment]
PR #10 fixes this issue.
